dark_theme: true
show_controls: true
start_with: ''
mode: chat-instruct
chat_style: cai-chat
prompt-default: QA
prompt-notebook: QA
preset: simple-1
max_new_tokens: 200
max_new_tokens_min: 1
max_new_tokens_max: 4096
seed: -1
negative_prompt: ''
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 32768
custom_stopping_strings: ''
auto_max_new_tokens: false
max_tokens_second: 0
ban_eos_token: false
custom_token_bans: ''
add_bos_token: true
skip_special_tokens: true
stream: true
name1: You
character: Joyce
instruction_template: Llama-v2
chat-instruct_command: |-
  Continue the chat dialogue below. Write a single reply acting as the character "<|character|>".

  <|prompt|>
instruction_template_str: |-
  {%- set ns = namespace(found=false) -%}
  {%- for message in messages -%}
      {%- if message['role'] == 'system' -%}
          {%- set ns.found = true -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if not ns.found -%}
      {{- '[INST] <<SYS>>\n' + 'Answer the questions.' + '\n<</SYS>>\n\n' -}}
  {%- endif %}
  {%- for message in messages %}
      {%- if message['role'] == 'system' -%}
          {{- '[INST] <<SYS>>\n' + message['content'] + '\n<</SYS>>\n\n' -}}
      {%- else -%}
          {%- if message['role'] == 'user' -%}
              {{-'' + message['content'] + ' [/INST] '-}}
          {%- else -%}
              {{-'' + message['content'] + ' </s><s>[INST] ' -}}
          {%- endif -%}
      {%- endif -%}
  {%- endfor -%}
  {%- if add_generation_prompt -%}
      {{-''-}}
  {%- endif -%}
chat_template_str: |-
  {%- for message in messages %}
    {%- if message['role'] == 'system' -%}
        {{- message['content'] + '\n\n' -}}
    {%- else -%}
        {%- if message['role'] == 'user' -%}
            {{-'' + message['content'] + ' [/INST] ' -}}
        {%- else -%}
            {{-'' + message['content'] + ' </s><s>[INST] ' -}}
        {%- endif -%}
    {%- endif -%}
  {%- endfor -%}
autoload_model: false
default_extensions:
- gallery
- silero_tts 
# - whisper_stt
- api
- superboogav2
- Training_PRO
# whisper_stt-whipser_language: chinese
# whisper_stt-whipser_model: base.en
# whisper_stt-auto_submit: True
silero_tts_mode: 'silero'
silero_tts-speaker: en_56
# silero_tts-language: English
silero_tts-model_id: v3_en
silero_tts-sample_rate: 48000
silero_tts-device: cuda # cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone
silero_tts-show_text: True
silero_tts-autoplay: True
silero_tts-voice_pitch: medium
silero_tts-voice_speed: medium
# silero_tts-local_cache_path: ''